import type { LLMModelConfig } from "../interfaces/llm-model-config";

export const TRANSFORMER_MODELS: LLMModelConfig[] = [
	{
		id: "onnx-community/granite-4.0-micro-ONNX-web",
		provider: "transformer",
		displayName: "Granite 4.0 Micro",
		sizeGB: 2.3,
		sizeLabel: "2.3GB",
		description: "🪨 Granite 4.0 Micro: IBM browser-tuned WebGPU model",
		contextLength: 128000,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 65_536,
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 86,
		performanceScore: 82,
		contextScore: 98,
		releaseDate: "2025-05",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/gemma-4-E2B-it-ONNX",
		provider: "transformer",
		displayName: "Gemma 4 E2B",
		sizeGB: 1.4,
		sizeLabel: "4.8GB",
		description: "💠 Gemma 4 E2B: Multimodal q4f16 WebGPU model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 70_912,
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 87,
		performanceScore: 78,
		contextScore: 60,
		releaseDate: "2025-05",
		quickDownload: true,
		runnerConfig: {
			runtime: "image_text_to_text",
			dtype: "auto",
			postprocess: "gemma_clean",
			webgpuMaxContextTokens: 8192,
		},
	},
	{
		id: "LiquidAI/LFM2.5-1.2B-Thinking-ONNX",
		provider: "transformer",
		displayName: "LFM2.5 1.2B Thinking",
		sizeGB: 0.854,
		sizeLabel: "854MB",
		description: "🌊 LFM2.5 Thinking: Reasoning-focused q4 WebGPU model",
		contextLength: 128000,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: 32_768,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 78,
		performanceScore: 84,
		contextScore: 98,
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "text_generation_pipeline",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2-8B-A1B-ONNX",
		provider: "transformer",
		displayName: "LFM2 8B-A1B",
		sizeGB: 4.8,
		sizeLabel: "4.8GB",
		description: "🌊 LFM2 8B-A1B: Mixture-of-experts q4f16 WebGPU model",
		contextLength: 32768,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: 57_344,
		requiresWebGPU: true,
		minMemoryGB: 8,
		qualityScore: 88,
		performanceScore: 60,
		contextScore: 85,
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2-24B-A2B-ONNX",
		provider: "transformer",
		displayName: "LFM2 24B-A2B",
		sizeGB: 13.5,
		sizeLabel: "13.5GB",
		description: "🌊 LFM2 24B-A2B: Large mixture-of-experts q4f16 WebGPU model",
		contextLength: 32768,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: 73_728,
		requiresWebGPU: true,
		minMemoryGB: 16,
		qualityScore: 92,
		performanceScore: 45,
		contextScore: 85,
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "HuggingFaceTB/SmolLM3-3B-ONNX",
		provider: "transformer",
		displayName: "SmolLM3 3B",
		sizeGB: 1.8,
		sizeLabel: "1.8GB",
		description: "🐭 SmolLM3 3B: Dual-mode reasoning, 128K context (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 110_592,
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 88,
		performanceScore: 82,
		contextScore: 98,
		releaseDate: "2025-07",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
		provider: "transformer",
		displayName: "DeepSeek-R1 Qwen 1.5B",
		sizeGB: 1.5,
		sizeLabel: "1.5GB",
		description: "🧠 DeepSeek-R1: Reasoning specialist, 128K context (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 28_672,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 85,
		performanceScore: 80,
		contextScore: 98,
		releaseDate: "2025-01",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen3-0.6B-ONNX",
		provider: "transformer",
		displayName: "Qwen 3 0.6B",
		sizeGB: 0.4,
		sizeLabel: "400MB",
		description: "🌐 Qwen 3 0.6B: Smallest, fastest, 32K context (WebGPU)",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 57_344,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 70,
		performanceScore: 92,
		contextScore: 85,
		releaseDate: "2025-04",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Phi-4-mini-instruct-ONNX-GQA",
		provider: "transformer",
		displayName: "Phi 4 Mini",
		sizeGB: 3.1,
		sizeLabel: "3.1GB",
		description: "🔬 Phi 4: ONNX GQA WebGPU build for browser inference",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 98_304,
		requiresWebGPU: true,
		minMemoryGB: 6,
		qualityScore: 89,
		performanceScore: 70,
		contextScore: 98,
		releaseDate: "2025-02",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-350M-ONNX",
		provider: "transformer",
		displayName: "LFM2 350M",
		sizeGB: 0.23,
		sizeLabel: "230MB",
		description: "🌊 LFM2: Ultra-compact language model (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 8_192,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 40,
		performanceScore: 98,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-700M-ONNX",
		provider: "transformer",
		displayName: "LFM2 700M",
		sizeGB: 0.45,
		sizeLabel: "410MB",
		description: "🌊 LFM2: Balanced performance model (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 15_360,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 60,
		performanceScore: 90,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-1.2B-ONNX",
		provider: "transformer",
		displayName: "LFM2 1.2B",
		sizeGB: 0.78,
		sizeLabel: "780MB",
		description: "🌊 LFM2: High-quality model (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 22_528,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 75,
		performanceScore: 80,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2.5-1.2B-Instruct-ONNX",
		provider: "transformer",
		displayName: "LFM2.5 1.2B Instruct",
		sizeGB: 0.709,
		sizeLabel: "900MB",
		description: "🌊 LFM2: specialist (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 22_528,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 72,
		performanceScore: 82,
		contextScore: 60,
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/SmolLM2-135M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 135M",
		sizeGB: 0.1,
		sizeLabel: "100MB",
		description: "SmolLM2 135M: ultra-light edge model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 12_288,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 30,
		performanceScore: 99,
		contextScore: 60,
		releaseDate: "2024-11",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/SmolLM2-360M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 360M",
		sizeGB: 0.23,
		sizeLabel: "230MB",
		description: "🐭 SmolLM2: Efficient edge model (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 24_576,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 45,
		performanceScore: 96,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/SmolLM2-1.7B-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 1.7B",
		sizeGB: 1.0,
		sizeLabel: "1.0GB",
		description: "SmolLM2 1.7B: compact general-purpose chat model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 49_152,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 65,
		performanceScore: 83,
		contextScore: 60,
		releaseDate: "2024-11",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen2.5-0.5B-Instruct",
		provider: "transformer",
		displayName: "Qwen 2.5 0.5B",
		sizeGB: 0.32,
		sizeLabel: "320MB",
		description: "🌐 Qwen2.5: Multilingual compact model (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 12_288,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 55,
		performanceScore: 95,
		contextScore: 98,
		releaseDate: "2024-09",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen2.5-1.5B-Instruct",
		provider: "transformer",
		displayName: "Qwen 2.5 1.5B",
		sizeGB: 0.9,
		sizeLabel: "900MB",
		description: "Qwen 2.5 1.5B: multilingual general chat model",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 28_672,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 72,
		performanceScore: 82,
		contextScore: 98,
		releaseDate: "2024-09",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Phi-4-mini-instruct",
		provider: "transformer",
		displayName: "Phi 4 Mini (Legacy ID)",
		sizeGB: 3.1,
		sizeLabel: "3.1GB",
		description:
			"Legacy Phi 4 browser ID kept only for unsupported-model messaging",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 98_304,
		requiresWebGPU: true,
		minMemoryGB: 6,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		releaseDate: "2025-02",
		unsupported: true,
		unsupportedReason:
			"onnx-community/Phi-4-mini-instruct does not expose the public browser-ready ONNX tokenizer files needed by this runtime. Use onnx-community/Phi-4-mini-instruct-ONNX-GQA instead.",
	},
	{
		id: "onnx-community/gemma-3-1b-it-ONNX",
		provider: "transformer",
		displayName: "Gemma 3 1B",
		sizeGB: 0.5,
		sizeLabel: "500MB",
		description: "Gemma 3 1B browser build currently disabled in this runtime",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 16_384,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		releaseDate: "2025-03",
		unsupported: true,
		unsupportedReason:
			"onnx-community/gemma-3-1b-it-ONNX is not currently reliable in the bundled transformers.js runtime in the browser. Use another transformer model or a Wllama GGUF Gemma model instead.",
	},
	{
		id: "onnx-community/gemma-3-270m-it",
		provider: "transformer",
		displayName: "Gemma 3 270M",
		sizeGB: 0.2,
		sizeLabel: "200MB",
		description:
			"Gemma 3 270M browser build currently disabled in this runtime",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 8_192,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		releaseDate: "2025-03",
		unsupported: true,
		unsupportedReason:
			"onnx-community/gemma-3-270m-it is not currently compatible with the bundled transformers.js runtime in the browser. Use a Wllama GGUF Gemma model or another transformer model such as Qwen3 or LFM2 instead.",
	},
];
